// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVxJmY09X9S8tMGtXhyqgJWF2n66nhPyM',
    appId: '1:32218984396:web:46ecedfd443fb6bc75f769',
    messagingSenderId: '32218984396',
    projectId: 'aibudgetapp',
    authDomain: 'aibudgetapp.firebaseapp.com',
    storageBucket: 'aibudgetapp.firebasestorage.app',
    measurementId: 'G-2HE2HP2B1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsKq1PnPgR4R8q1ANps6cfeobivteyf-o',
    appId: '1:32218984396:android:87d1a065d2acc7aa75f769',
    messagingSenderId: '32218984396',
    projectId: 'aibudgetapp',
    storageBucket: 'aibudgetapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBchZ-LzMz5NHMnDybv3XIKjPNn25rJG90',
    appId: '1:32218984396:ios:4647e48a053363f175f769',
    messagingSenderId: '32218984396',
    projectId: 'aibudgetapp',
    storageBucket: 'aibudgetapp.firebasestorage.app',
    iosBundleId: 'com.example.aiBudgetingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBchZ-LzMz5NHMnDybv3XIKjPNn25rJG90',
    appId: '1:32218984396:ios:4647e48a053363f175f769',
    messagingSenderId: '32218984396',
    projectId: 'aibudgetapp',
    storageBucket: 'aibudgetapp.firebasestorage.app',
    iosBundleId: 'com.example.aiBudgetingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVxJmY09X9S8tMGtXhyqgJWF2n66nhPyM',
    appId: '1:32218984396:web:ad1fd703ac39272575f769',
    messagingSenderId: '32218984396',
    projectId: 'aibudgetapp',
    authDomain: 'aibudgetapp.firebaseapp.com',
    storageBucket: 'aibudgetapp.firebasestorage.app',
    measurementId: 'G-8D45HZHDCT',
  );
}
